---
# tasks file for htpc-common

# BLOCK: Configure SSH service
- block:

  - name: Make sure SSH server is installed for remote access
    apt: name=openssh-server state=installed update_cache=yes cache_valid_time=3600

  - name: Make sure SSH is started on boot
    service: name=ssh state=started enabled=yes
  
  tags: ssh
  when: htpc_ssh_service

# BLOCK: Create htpc group and user, enable sudo access
- block:

  - name: Create htpc group
    group: name={{ htpc_user_group }} state=present

  - name: Create htpc user
    user: 
      name={{ htpc_user_username }}
      password={{ htpc_user_password }}
      group={{ htpc_user_group }}
      update_password=on_create
      state=present 
      createhome=yes 
      shell={{ htpc_user_shell }} 
      groups=adm,plugdev,dialout,cdrom,audio,video
      append=yes
    register: htpc_user_verify_user

  - name: Set Fact "htpc_user_uid"
    set_fact: htpc_user_uid={{ htpc_user_verify_user.uid }}

  - name: Set Fact "htpc_user_gid"
    set_fact: htpc_user_gid={{ htpc_user_verify_user.group }}

  - name: Enable sudo for htpc user
    user: 
      name={{ htpc_user_username }}
      groups=sudo
      append=yes
    when: htpc_user_sudo_access
  
  tags:
    - createuser

# Create media folders
- block:
  - name: Create Media Folders
    file: path={{ item }} state=directory owner={{ htpc_user_username }} group={{ htpc_user_group }} mode=0755 recurse=yes
    with_items:
    - "{{ htpc_media_path }}/{{ htpc_media_movies }}"
    - "{{ htpc_media_path }}/{{ htpc_media_tv }}"
    - "{{ htpc_media_path }}/{{ htpc_media_music }}"
    - "{{ htpc_media_path }}/{{ htpc_media_pictures }}"
    when: htpc_create_media_folders
    tags:
    - media

  - name: Create Downloads Folders
    file: path={{ item }} state=directory owner={{ htpc_user_username }} group={{ htpc_user_group }} mode=0755 recurse=yes
    with_items:
    - "{{ htpc_downloads_complete }}"
    - "{{ htpc_downloads_incomplete }}"

  - name: Create Processing Folders
    file: path={{ item }} state=directory owner={{ htpc_user_username }} group={{ htpc_user_group }} mode=0755 recurse=yes
    with_items:
    - "{{ htpc_downloads_incomplete }}/process/"
    - "{{ htpc_downloads_incomplete }}/process/{{ htpc_media_movies }}"
    - "{{ htpc_downloads_incomplete }}/process/{{ htpc_media_tv }}"
    - "{{ htpc_downloads_incomplete }}/process/{{ htpc_media_music }}"

  tags:
    - mediafolders